plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "pythonbug's blog"
email: pythonbug@gmail.com
description: ""
github:
  username: pythonbug
swiftype:
  searchId: EYbgqaK5TUZHsdVftT4g
gitment:
    repo: blog
    client_id: f5765129272972459c49
    client_secret: 8ea0aeae0f4d776b1f127a014e4e4557089ac3cf

url: "https://www.pythonbug.com"
imgrepo: "https://bit-ranger.github.io/blog/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

