plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "pythonbug's blog"
email: xuyang5188@outlook.com
description: ""
github:
  username: pythonbug
swiftype:
  searchId: EeJfxJwA2kryPskPZocb
swift_search:
      enable: true
# Gitalk settings
comment_gitalk_clientId: d67b9f374f6972290aee
comment_gitalk_clientSecret: 4cac134f9a3c7cb6542de9a1920892a740a38ab8
comment_gitalk_repo: https://github.com/pythonbug/blogtalk
github_username: pythonbug

#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

