plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo: https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: #fromendworld@outlook.com 
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: #FromEndWorld/loffer #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "pythonbug"
email: pythonbug@gmail.com
description: "一个程序员"
github:
  username: pythonbug
swiftype:
  searchId: 
# 站点页脚的文字
footer-text: Copyright (c) 2019 来自中世界

# 评论，注意，请不要同时添加多种不同的评论区

# 输入Disqus shortname，即可添加评论区
disqus: www.pythonbug.com

# 输入Gitalk相关设定，即可添加评论区
# gitalk:
  clientID: cca390d808085e620207
  clientSecret: 8c319d0c4ecd156f3e73e3652936a17e257cd70a
  repo: blogtalk
  owner: pythonbug
  admin: pythonbug

url: "https://www.pythonbug.com"
imgrepo: "https://bit-ranger.github.io/blog/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

